#!/bin/bash
# ============================================================
# QUILLYOS SESSION HANDOFF — PUSH SCRIPT
# For Termux / PicoClaw / Linux environments
# ============================================================

set -e

REPO_URL="https://github.com/YOUR_USERNAME/quillyos-foundation.git"
LOCAL_DIR="$HOME/quillyos-foundation"
BRIEF_DIR="$LOCAL_DIR/session_briefs"

# --- Arguments ---
SUMMARY="${1:-Session ended}"
AGENT_ROLE="${2:-picoclaw}"

# --- Generate timestamp ---
TIMESTAMP=$(date +"%Y-%m-%d_%H-%M")
BRIEF_ID=$(date +"%s")
FILENAME="$TIMESTAMP-$AGENT_ROLE-$BRIEF_ID.md"
FILEPATH="$BRIEF_DIR/$FILENAME"

echo "========================================"
echo "  QUILLYOS SESSION HANDOFF"
echo "  Push session brief"
echo "========================================"
echo ""

# --- Check dependencies ---
if ! command -v git &> /dev/null; then
    echo "[ERROR] git is not installed. Install with: pkg install git"
    exit 1
fi

# --- Ensure repo exists ---
if [ ! -d "$LOCAL_DIR/.git" ]; then
    echo "[INFO] Repository not found. Cloning..."
    git clone "$REPO_URL" "$LOCAL_DIR"
fi

cd "$LOCAL_DIR"

# --- Pull latest to avoid conflicts ---
echo "[INFO] Pulling latest changes..."
git pull origin main || true

# --- Generate brief template ---
echo "[INFO] Generating brief: $FILENAME"

cat > "$FILEPATH" << EOF
# SESSION BRIEF — $AGENT_ROLE — $(date +"%Y-%m-%d")
## Session ID: $BRIEF_ID
## Status: complete

---

## 1. SESSION CONTEXT

**Agent:** $AGENT_ROLE
**Date Started:** [Fill in]
**Date Ended:** $(date -Iseconds)
**Duration:** [Fill in]
**Platform:** Termux / PicoClaw

---

## 2. MISSION CONTEXT

**Active Mission:** [Reference mission ID]
**Context Matrix:** [Reference context matrix]
**North Star Alignment:** [Which vision this serves]

---

## 3. WHAT WAS DONE

### Completed
- [ ] $SUMMARY

### In Progress
- [ ] [Fill in]

### Blocked
- [ ] [Fill in]

---

## 4. DECISIONS MADE

| Decision | Rationale | Reversibility | Status |
|----------|-----------|---------------|--------|
| [Fill in] | [Fill in] | [Fill in] | [Fill in] |

---

## 5. KNOWLEDGE GENERATED

### New Artifacts
- [Fill in]

### Updated Knowledge
- [Fill in]

### Open Questions Raised
- [Fill in]

---

## 6. AGENT STATE

### Context Loaded
- [Fill in]

### Skills Used
- [Fill in]

### Workflows Triggered
- [Fill in]

---

## 7. NEXT SESSION PREP

### Recommended Next Actions
1. [Fill in]
2. [Fill in]

### Context to Load
- [Fill in]

### Warnings / Notes
- [Fill in]

---

## 8. EVIDENCE & REFERENCES

### Git Commits
- [Fill in]

### Files Modified
- [Fill in]

### External References
- [Fill in]

---

*Generated by $AGENT_ROLE at $(date -Iseconds)*
*Next session: run ./scripts/handoff.sh to continue*
EOF

# --- Update LATEST.md ---
cp "$FILEPATH" "$BRIEF_DIR/LATEST.md"

# --- Commit and push ---
echo "[INFO] Committing and pushing..."
git add session_briefs/
git commit -m "session handoff: $AGENT_ROLE — $BRIEF_ID" || echo "[WARN] Nothing to commit"
git push origin main

echo ""
echo "========================================"
echo "  HANDOFF PUSHED SUCCESSFULLY"
echo "========================================"
echo ""
echo "Brief: $FILENAME"
echo "Location: session_briefs/$FILENAME"
echo ""
echo "Next session: run ./scripts/handoff.sh"
