#!/data/data/com.termux/files/usr/bin/bash
# =============================================================================
# QUILLYOS AGENT SUITE v1.0
# Unified command interface for PicoClaw-Termux agentic layer
# Plain-language session handoff + legacy PicoClaw bridge
# Repository: q-u-i-l-l-y/quillyos-foundation
# =============================================================================

# --- CONFIGURATION ---
REPO_URL="https://github.com/q-u-i-l-l-y/quillyos-foundation"
REPO_DIR="$HOME/quillyos/quillyos-foundation"
BRIEF_DIR="$REPO_DIR/session_briefs"
LATEST_BRIEF="$BRIEF_DIR/LATEST.md"
NEXUS_DIR="$HOME/quillyos/quillyos-nexus"  # Future

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# =============================================================================
# CORE FUNCTIONS
# =============================================================================

show_header() {
    echo -e "${CYAN}"
    echo "========================================"
    echo "  QUILLYOS AGENT SUITE v1.0"
    echo "  PicoClaw · Kimi · Nexus Protocol"
    echo "========================================"
    echo -e "${NC}"
}

show_footer() {
    echo -e "${CYAN}"
    echo "========================================"
    echo "  Build for decades. Not versions. 🚀"
    echo "========================================"
    echo -e "${NC}"
}

check_repo() {
    if [ ! -d "$REPO_DIR/.git" ]; then
        echo -e "${RED}[ERROR] Repository not found at $REPO_DIR${NC}"
        echo "Run: bash -c \"\$(curl -fsSL $REPO_URL/raw/main/scripts/install.sh)\""
        exit 1
    fi
}

# =============================================================================
# SESSION HANDOFF COMMANDS
# =============================================================================

cmd_pull_brief() {
    check_repo
    cd "$REPO_DIR"
    echo -e "${BLUE}[INFO] Pulling latest brief from GitHub...${NC}"
    git pull origin main --quiet
    if [ -f "$LATEST_BRIEF" ]; then
        echo ""
        cat "$LATEST_BRIEF"
        echo ""
        show_footer
    else
        echo -e "${YELLOW}[WARN] No brief found.${NC}"
    fi
}

cmd_pull_brief_clip() {
    check_repo
    cd "$REPO_DIR"
    git pull origin main --quiet
    if [ -f "$LATEST_BRIEF" ]; then
        cat "$LATEST_BRIEF" | termux-clipboard-set
        echo -e "${GREEN}[✓] Brief copied to clipboard.${NC}"
        echo "Paste into Kimi to continue session."
    else
        echo -e "${RED}[ERROR] No brief found.${NC}"
    fi
}

cmd_pull_brief_kimi() {
    check_repo
    cd "$REPO_DIR"
    git pull origin main --quiet
    if [ -f "$LATEST_BRIEF" ]; then
        echo ""
        echo "=== KIMI SESSION CONTEXT ==="
        echo ""
        echo "Paste the following into your Kimi session:"
        echo ""
        echo "```"
        echo "# QUILLYOS SESSION CONTEXT"
        echo "# Retrieved from: $REPO_URL"
        echo "# Timestamp: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
        echo ""
        cat "$LATEST_BRIEF"
        echo ""
        echo "```"
        echo ""
        echo "=== END CONTEXT ==="
    else
        echo -e "${RED}[ERROR] No brief found.${NC}"
    fi
}

cmd_push_brief() {
    check_repo
    if [ -z "$1" ]; then
        echo -e "${RED}[ERROR] Usage: push-brief \"Your session summary\"${NC}"
        exit 1
    fi

    cd "$REPO_DIR"
    echo -e "${BLUE}[INFO] Pulling latest changes...${NC}"
    git pull origin main --quiet

    TIMESTAMP=$(date +"%Y-%m-%d_%H-%M")
    EPOCH=$(date +%s)
    BRIEF_FILE="session_briefs/${TIMESTAMP}-picoclaw-${EPOCH}.md"

    echo -e "${BLUE}[INFO] Generating brief: ${BRIEF_FILE}${NC}"

    cat > "$BRIEF_FILE" << EOF
# SESSION BRIEF — PicoClaw (Termux) — $(date +"%Y-%m-%d")
## Session ID: $(date +"%Y-%m-%d")-picoclaw-${EPOCH}
## Status: complete
## Agent: PicoClaw (Termux Local Node)
## Platform: Termux (Android)
## Repository: \`q-u-i-l-l-y/quillyos-foundation\`

---

## 1. SESSION CONTEXT

**Date Started:** $(date -u +"%Y-%m-%dT%H:%M:%SZ")
**Date Ended:** $(date -u +"%Y-%m-%dT%H:%M:%SZ")
**Duration:** Active session
**Node:** picoclaw-termux
**Mission:** mission-002 — Legacy System Integration & Foundation Bridging

---

## 2. WHAT WAS DONE

### Completed
- [x] $1

### Session Notes
$(if [ -f "$REPO_DIR/.session_notes" ]; then cat "$REPO_DIR/.session_notes"; else echo "_No additional notes recorded._"; fi)

---

## 3. NEXT ACTIONS

- [ ] Continue from this brief in next session
- [ ] Run \`pull-brief\` to retrieve latest context

---

*Generated by PicoClaw (Termux) at $(date -u +"%Y-%m-%dT%H:%M:%SZ")*
*Repository: $REPO_URL*
EOF

    # Update LATEST.md
    cp "$BRIEF_FILE" "$LATEST_BRIEF"

    echo -e "${BLUE}[INFO] Committing and pushing...${NC}"
    git add session_briefs/
    git commit -m "session handoff: picoclaw — ${EPOCH}" --quiet

    if git push origin main; then
        echo ""
        echo -e "${GREEN}========================================${NC}"
        echo -e "${GREEN}  HANDOFF PUSHED SUCCESSFULLY${NC}"
        echo -e "${GREEN}========================================${NC}"
        echo ""
        echo "Brief: ${BRIEF_FILE}"
        echo "Location: session_briefs/"
        echo ""
        echo "Next session: run pull-brief"

        # Clear session notes after push
        rm -f "$REPO_DIR/.session_notes"
    else
        echo -e "${RED}[ERROR] Push failed.${NC}"
        echo "Your brief is saved locally at: $BRIEF_FILE"
    fi
}

# =============================================================================
# NEW AGENTIC COMMANDS
# =============================================================================

cmd_session_status() {
    check_repo
    cd "$REPO_DIR"
    git pull origin main --quiet 2>/dev/null

    echo -e "${CYAN}"
    echo "=== SESSION STATUS ==="
    echo -e "${NC}"
    echo "Repository: $REPO_URL"
    echo "Local path: $REPO_DIR"
    echo "Latest brief: $(ls -t session_briefs/*.md 2>/dev/null | head -1 | xargs basename 2>/dev/null || echo 'None')"
    echo "Git status: $(git status --short | wc -l) uncommitted changes"
    echo ""

    if [ -f "$REPO_DIR/.session_notes" ]; then
        echo -e "${YELLOW}Session notes pending push:${NC}"
        cat "$REPO_DIR/.session_notes"
        echo ""
    fi

    echo -e "${CYAN}Available commands:${NC}"
    echo "  session push \"text\"  — Record session summary"
    echo "  session status       — Show this status"
    echo "  session log          — List all briefs"
    echo "  session sync         — Pull latest + push local"
    echo "  insight add \"text\"   — Add insight to current session"
    echo "  insight list         — Show pending insights"
}

cmd_session_log() {
    check_repo
    cd "$REPO_DIR"
    echo -e "${CYAN}=== SESSION HISTORY ===${NC}"
    echo ""
    ls -lt session_briefs/*.md 2>/dev/null | while read line; do
        file=$(echo "$line" | awk '{print $NF}')
        name=$(basename "$file")
        date=$(echo "$line" | awk '{print $6, $7, $8}')
        echo "  $date  $name"
    done
    echo ""
    echo "Use 'pull-brief' to load the latest."
}

cmd_session_sync() {
    check_repo
    cd "$REPO_DIR"
    echo -e "${BLUE}[INFO] Syncing with GitHub...${NC}"
    git pull origin main
    if [ -n "$(git status --short)" ]; then
        echo -e "${YELLOW}[WARN] Local changes detected. Commit or stash before sync.${NC}"
    else
        echo -e "${GREEN}[✓] Repository is in sync.${NC}"
    fi
}

cmd_insight_add() {
    check_repo
    if [ -z "$1" ]; then
        echo -e "${RED}[ERROR] Usage: insight add \"Your insight\"${NC}"
        exit 1
    fi

    echo "- $(date +"%H:%M"): $1" >> "$REPO_DIR/.session_notes"
    echo -e "${GREEN}[✓] Insight recorded. Push session to persist.${NC}"
}

cmd_insight_list() {
    check_repo
    if [ -f "$REPO_DIR/.session_notes" ]; then
        echo -e "${CYAN}=== PENDING INSIGHTS ===${NC}"
        cat "$REPO_DIR/.session_notes"
        echo ""
        echo "Run 'session push \"summary\"' to persist these insights."
    else
        echo -e "${YELLOW}No pending insights. Use 'insight add' to record one.${NC}"
    fi
}

# =============================================================================
# LEGACY PICOCLAW BRIDGE
# =============================================================================

cmd_picoclaw_status() {
    if command -v picoclaw &> /dev/null; then
        echo -e "${GREEN}[✓] PicoClaw binary found.${NC}"
        picoclaw version 2>/dev/null || echo "Version check failed."

        if [ -d "$HOME/.picoclaw" ]; then
            echo -e "${GREEN}[✓] PicoClaw workspace exists.${NC}"
            echo "Config: $HOME/.picoclaw/config.json"
            echo "Workspace: $HOME/.picoclaw/workspace/"
        else
            echo -e "${YELLOW}[!] PicoClaw not initialized. Run: picoclaw onboard${NC}"
        fi
    else
        echo -e "${YELLOW}[!] PicoClaw binary not found.${NC}"
        echo "Download: wget https://github.com/sipeed/picoclaw/releases/latest/download/picoclaw_Linux_arm64.tar.gz"
    fi
}

cmd_picoclaw_chat() {
    if [ -z "$1" ]; then
        echo -e "${RED}[ERROR] Usage: picoclaw-chat \"Your message\"${NC}"
        exit 1
    fi

    if command -v picoclaw &> /dev/null; then
        echo -e "${BLUE}[PicoClaw] $1${NC}"
        picoclaw agent -m "$1" 2>/dev/null || echo "PicoClaw agent execution failed."
    else
        echo -e "${RED}[ERROR] PicoClaw not installed.${NC}"
    fi
}

# =============================================================================
# QUICK REFERENCE COMMANDS
# =============================================================================

cmd_qstatus() {
    check_repo
    cd "$REPO_DIR"
    git status
}

cmd_qcd() {
    cd "$REPO_DIR"
    echo "Navigated to: $REPO_DIR"
    exec bash
}

cmd_qfoundation() {
    check_repo
    cat "$REPO_DIR/FOUNDATION.md" 2>/dev/null || echo "FOUNDATION.md not found."
}

cmd_qroadmap() {
    check_repo
    cat "$REPO_DIR/roadmap/IMMEDIATE_MILESTONES.md" 2>/dev/null || echo "Roadmap not found."
}

cmd_qprinciples() {
    check_repo
    cat "$REPO_DIR/principles/CORE_PRINCIPLES.md" 2>/dev/null || echo "Principles not found."
}

cmd_qagents() {
    check_repo
    cat "$REPO_DIR/governance/AGENT_SPECIALIZATION.md" 2>/dev/null || echo "Agent specs not found."
}

cmd_qontology() {
    check_repo
    cat "$REPO_DIR/ontology/CANONICAL_OBJECT_TYPES.md" 2>/dev/null || echo "Ontology not found."
}

cmd_qprotocol() {
    check_repo
    cat "$REPO_DIR/protocol/NEXUS_PROTOCOL_SPEC.md" 2>/dev/null || echo "Protocol spec not found."
}

cmd_qhandoff() {
    check_repo
    cat "$REPO_DIR/protocol/SESSION_HANDOFF.md" 2>/dev/null || echo "Handoff spec not found."
}

# =============================================================================
# MAIN DISPATCH
# =============================================================================

show_help() {
    show_header
    echo "Unified command interface for QuillyOS agent coordination."
    echo ""
    echo -e "${CYAN}SESSION HANDOFF${NC}"
    echo "  pull-brief              — Pull and display latest brief"
    echo "  pull-brief-clip         — Copy brief to clipboard"
    echo "  pull-brief-kimi         — Format brief for Kimi ingestion"
    echo "  push-brief \"text\"      — Push session brief to GitHub"
    echo ""
    echo -e "${CYAN}AGENTIC COMMANDS${NC}"
    echo "  session push \"text\"    — Alias for push-brief (plain language)"
    echo "  session status          — Show current session state"
    echo "  session log             — List all session briefs"
    echo "  session sync            — Pull latest + check sync status"
    echo "  insight add \"text\"     — Record insight (accumulates until push)"
    echo "  insight list            — Show pending insights"
    echo ""
    echo -e "${CYAN}LEGACY PICOCLAW BRIDGE${NC}"
    echo "  picoclaw-status         — Check PicoClaw daemon/workspace"
    echo "  picoclaw-chat \"text\"   — Send message to PicoClaw agent"
    echo ""
    echo -e "${CYAN}QUICK REFERENCE${NC}"
    echo "  qstatus                 — Check git status"
    echo "  qcd                     — Navigate to foundation repo"
    echo "  qfoundation             — Display FOUNDATION.md"
    echo "  qroadmap                — Display roadmap"
    echo "  qprinciples             — Display core principles"
    echo "  qagents                 — Display agent specializations"
    echo "  qontology               — Display canonical object types"
    echo "  qprotocol               — Display Nexus Protocol spec"
    echo "  qhandoff                — Display handoff mechanism"
    echo ""
    echo -e "${CYAN}PLAIN-LANGUAGE EXAMPLES${NC}"
    echo "  session push \"Verified Termux auth. Ready for legacy audit.\""
    echo "  insight add \"Need to map config.autonomous.json to Context Matrix\""
    echo "  picoclaw-chat \"What skills are installed?\""
    echo ""
    show_footer
}

# Determine which command to run
COMMAND="$1"
shift || true

case "$COMMAND" in
    # Legacy aliases (backward compatible)
    pull-brief)          cmd_pull_brief ;;
    pull-brief-clip)     cmd_pull_brief_clip ;;
    pull-brief-kimi)     cmd_pull_brief_kimi ;;
    push-brief)          cmd_push_brief "$*" ;;

    # New agentic commands
    session)
        SUBCMD="$1"
        shift || true
        case "$SUBCMD" in
            push)     cmd_push_brief "$*" ;;
            status)   cmd_session_status ;;
            log)      cmd_session_log ;;
            sync)     cmd_session_sync ;;
            *)        echo -e "${RED}[ERROR] Unknown session subcommand: $SUBCMD${NC}"; echo "Usage: session {push|status|log|sync}"; exit 1 ;;
        esac
        ;;

    insight)
        SUBCMD="$1"
        shift || true
        case "$SUBCMD" in
            add)      cmd_insight_add "$*" ;;
            list)     cmd_insight_list ;;
            *)        echo -e "${RED}[ERROR] Unknown insight subcommand: $SUBCMD${NC}"; echo "Usage: insight {add|list}"; exit 1 ;;
        esac
        ;;

    # PicoClaw bridge
    picoclaw-status)     cmd_picoclaw_status ;;
    picoclaw-chat)       cmd_picoclaw_chat "$*" ;;

    # Quick reference
    qstatus)             cmd_qstatus ;;
    qcd)                 cmd_qcd ;;
    qfoundation)         cmd_qfoundation ;;
    qroadmap)            cmd_qroadmap ;;
    qprinciples)         cmd_qprinciples ;;
    qagents)             cmd_qagents ;;
    qontology)           cmd_qontology ;;
    qprotocol)           cmd_qprotocol ;;
    qhandoff)            cmd_qhandoff ;;

    # Help / default
    help|--help|-h|"")
        show_help ;;

    *)
        echo -e "${RED}[ERROR] Unknown command: $COMMAND${NC}"
        echo "Run 'quillyos help' for available commands."
        exit 1
        ;;
esac
